---
- name: Disable root SSH login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: Restart SSH

- name: Set UFW default policies
  ufw:
    state: enabled
    policy: deny
    direction: incoming

- name: Allow SSH and Docker
  ufw:
    rule: allow
    name: "{{ item }}"
  loop:
    - OpenSSH

- name: Allow Docker API Port 2375
  ufw:
    rule: allow
    port: 2375
    proto: tcp


